[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --html=reports/report.html --self-contained-html -s --tb=short

markers =
    smoke: 冒烟测试
    regression: 回归测试
    ui: UI 测试

log_cli = true
log_cli_level = INFO
